### ISSUE TITLE
ID da cidade está "hardcode" em Candidato

### ISSUE THREAD

**Issue by jesuino** [pedrorocha-net/eleicoes2016-rj-comparadoacoes#3]
É necessário também modificar o ID do candidato na classe Candidato:

https://github.com/pedrorocha-net/eleicoes2016-rj-comparadoacoes/blob/master/data/crawler/Candidato.php

Assim, somente a modificação do ID em generate não está sendo suficiente.

Talvez passar o ID da cidade no construtor do Candidato?

**Comment by pedrorocha-net** [comment]
Ajustei ali, para ficar mais fácil de alguém reaproveitar e alterar.

**Comment by jesuino** [comment]
obrigado :)

## 

_William Antônio Siqueira_
_Java Support Analyst_

_http://fxapps.blogspot.com http://fxapps.blogspot.com_
_http://www.williamantonio.wordpress.com
http://www.williamantonio.wordpress.com_
_http://williamprogrammer.com http://williamprogrammer.com_

2016-09-25 19:46 GMT-03:00 Pedro Rocha notifications@github.com:
