### ISSUE TITLE
Erro ao executar 'npm install'

### ISSUE THREAD

**Issue by netoeuler** [pedrorocha-net/eleicoes2016-rj-comparadoacoes#5]
Estou usando a versão 1.4.21 e ao executar esse comando aparece a mensagem:

npm ERR! node-sass@3.10.0 install: `node scripts/install.js`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the node-sass@3.10.0 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

**Comment by corvolino** [comment]
Qual teu SO? Eu fiz o procedimento no OS X e o npm foi tranquilo. Baixei o node e rodei e funcionou.

**Comment by netoeuler** [comment]
Debian 8. Tinha acabado de baixar o NPM via apt-get e ainda dei update antes de instalar.

**Comment by pedrorocha-net** [comment]
Isso é uma questão do NodeJS no Debian. https://github.com/sass/node-sass/issues/1601

**Comment by pedrorocha-net** [comment]
Caso n consiga resolver por lá(tenho praticamente certeza de que conseguirá, peço q abra novamente aqui.

**Comment by netoeuler** [comment]
Seguindo o que foi explicado no link, foi resolvido através do comando:
`ln -s /usr/bin/nodejs /usr/bin/node`
