### ISSUE TITLE
gerar generate.php

### ISSUE THREAD

**Issue by corvolino** [pedrorocha-net/eleicoes2016-rj-comparadoacoes#6]
Olá tudo bom?

Ao tentar gerar o novo php encontrei este erro relacionado ao foreach. Alguém passou por isso?

> Warning: Invalid argument supplied for foreach() in /Applications/XAMPP/xamppfiles/htdocs/eleicoes2016-rj-comparadoacoes-master/data/crawler/generate.php on line 43

**Comment by pedrorocha-net** [comment]
Você usou isso com qual cidade? Esse erro acontece somente se um candidato não tiver nenhuma receita informada, creio eu.

**Comment by corvolino** [comment]
Na cidade que resido. Tem dois candidatos que não receberam nenhuma doação, vi pelo site do TSE.
