### ISSUE TITLE
Utilização do gulp

### ISSUE THREAD

**Issue by netoeuler** [pedrorocha-net/eleicoes2016-rj-comparadoacoes#7]
Não tenho familiaridade com NPM.

Teria como ser mais específico no passo abaixo? Visto que ao procurar esse caminho não obtive resultado.
Abra `dist/index.html` no seu navegador.

Também não tive como executar o passo seguinte pois o comando 'gulp' não existe. Ao fazer uma busca percebi que há um link com esse nome em 'node_modules' então executei o comando:
`node_modules/.bin/gulp deploy`

Ao executar o comando acima retornou a mensagem abaixo porém não vi mudanças.
[09:02:26] Requiring external module coffee-script/register
[09:02:26] Using gulpfile /eleicoes2016-aracaju-comparadoacoes/gulpfile.coffee
[09:02:26] Starting 'deploy'...
[09:02:27] [gh-pages] No files in the stream.
[09:02:27] Finished 'deploy' after 244 ms

Tem que ser feita alguma configuração a mais para utilização desse comando?

**Comment by pedrorocha-net** [comment]
Melhorei a documentação no README.md do projeto. Veja se te contempla.

**Comment by netoeuler** [comment]
Agora sim!
